export const pets = [
    {
        id: (Math.random()*3).toFixed(5),
        image: 'https://s.yimg.com/ny/api/res/1.2/LRESSShwNplSJ7gFxqHtmQ--/YXBwaWQ9aGlnaGxhbmRlcjt3PTY0MDtoPTQ3Nw--/https://media.zenfs.com/en/homerun/feed_manager_auto_publish_494/5f2acfff720e9a2c822eaa0b4f37e3dd',
        name: 'Mancha',
        age: '3 años',
        size: 'mediano',
        color: 'blanco y negro',
        description: 'Mancha es un perrito muy sociable',
    },
    {
        id: (Math.random()*3).toFixed(5),
        image: 'https://w7.pngwing.com/pngs/933/627/png-transparent-puppy-puppy-animal-puppy-clipart-thumbnail.png',
        name: 'Manchita',
        age: '1 año',
        size: 'pequeño',
        color: 'blanco y marron',
        description: 'Manchita no es un perrito muy sociable',
    },
    {
        id: (Math.random()*3).toFixed(5),
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKwpY3T06WzUOn-QqOYUDwMfWXlOGZNN6BAA&usqp=CAU',
        name: 'Manchon',
        age: '3 semanas',
        size: 'Muy pequeño',
        color: 'blanco y negro',
        description: 'Mancho es un perrito recien nacido',
    },
    {
        id: (Math.random()*3).toFixed(5),
        image: 'https://media.diariouno.com.ar/p/f54249878a58173518d1bc7ec8f5814e/adjuntos/298/imagenes/008/806/0008806731/1200x0/smart/perro-callejerojpg.jpg',
        name: 'Firulais',
        age: '7 años',
        size: 'Grande',
        color: 'Marron',
        description: 'Tranquilo y con mucha paciencia',
    },
    {
        id: (Math.random()*3).toFixed(5),
        image: 'https://cdn.wamiz.fr/cdn-cgi/image/format=auto,quality=80,width=1200,height=675,fit=cover/article/main-picture/617a613c7592b284460012.jpg',
        name: 'Firu',
        age: '4 años',
        size: 'Grande',
        color: 'gris y negro',
        description: 'Firu es muy amigable y busca ser adoptado hace muchos años',
    },
    {
        id: (Math.random()*3).toFixed(5),
        image: 'https://i2.wp.com/revista.weepec.com/wp-content/uploads/2017/08/perro-callejero.jpg?resize=500%2C335&ssl=1',
        name: 'Pichicho',
        age: '12 semanas',
        size: 'Pequeño',
        color: 'blanco',
        description: 'Pichicho quiere una nueva familia con la que pueda jugar',
    },
]