const petsData = [
  {
    name: "Toby",
    age: "8 años",
    species: "perro",
    image:
      "https://cdnb.20m.es/animalesenadopcion/files/2015/04/a1-620x465.jpg",
    size: "grande",
    color: "negro",
    sex: "macho",
    temperament: "tranquilo",
    adopted: "no",
    userId: 3,
  },
  {
    name: "Thor",
    age: "1 año",
    species: "perro",
    image: "https://acortar.link/iPCotm",
    size: "pequeño",
    color: "marron y blanco",
    sex: "macho",
    temperament: "inquieto",
    adopted: "no",
    userId: 2,
  },
  {
    name: "Chipirón",
    age: "6 meses",
    species: "perro",
    image:
      "https://thumbs.dreamstime.com/z/perro-mezclado-blanco-y-negro-de-la-raza-96823458.jpg",
    size: "mediano",
    color: "blanco",
    sex: "macho",
    temperament: "alegre",
    adopted: "no",
    userId: 3,
  },
  {
    name: "Bimba",
    age: "3 años",
    species: "perro",
    image:
      "https://www.molaunhuevo.com/wp-content/uploads/2014/06/border-collie.jpg",
    size: "mediano",
    color: "blanco y negro",
    sex: "hembra",
    temperament: "confiable",
    adopted: "no",
    userId: 4,
  },
  {
    name: "Trufa",
    age: "3 años",
    species: "perro",
    image:
      "https://t1.ea.ltmcdn.com/es/posts/0/2/5/16_pastor_leones_24520_15_600.jpg",
    size: "mediano",
    color: "negro con manchas blancas",
    sex: "hembra",
    temperament: "cuidadora",
    adopted: "no",
    userId: 5,
  },
  {
    name: "Pupi",
    age: "9 meses",
    species: "perro",
    image: "https://acortar.link/BuCrm0",
    size: "pequeño",
    color: "blanco",
    sex: "hembra",
    temperament: "afable",
    adopted: "no",
    userId: 6,
  },
  {
    name: "Bigotes",
    age: "2 años",
    species: "gato",
    image: "https://t2.ea.ltmcdn.com/es/posts/8/1/2/maine_coon_25218_3_600.jpg",
    size: "mediano",
    color: "anaranjado",
    sex: "hembra",
    temperament: "jugueton",
    adopted: "no",
    userId: 7,
  },
  {
    name: "Manchas",
    age: "4 años",
    species: "gato",
    image:
      "https://image.europafm.com//clipping/cmsimages01//2015/12/29/E3CDD244-FAC7-45D1-B33D-7032A7C22C49/30.jpg",
    size: "mediano",
    color: "tricolor",
    sex: "macho",
    temperament: "",
    adopted: "no",
    userId: 8,
  },
  {
    name: "Café con leche",
    age: "6 años",
    species: "perro",
    image: "https://pbs.twimg.com/media/DcjV8GyXUAI7P-u.jpg",
    size: "mediano",
    color: "cafe y blanco",
    sex: "macho",
    temperament: "jugueton",
    adopted: "no",
    userId: 5,
  },
  {
    name: "Ron",
    age: "3 años",
    species: "gato",
    image:
      "https://static.vecteezy.com/system/resources/previews/002/857/818/non_2x/orange-tabby-cat-photo.jpg",
    size: "mediano",
    color: "naranja",
    sex: "macho",
    temperament: "inquieto",
    adopted: "no",
    userId: 2,
  },
  {
    name: "Simba",
    age: "1 año",
    species: "gato",
    image:
      "https://www.feelcats.com/wp-content/uploads/2018/10/gato-atigrado-tic-ticked.jpg",
    size: "mediano",
    color: "gris",
    sex: "macho",
    temperament: "relajado",
    adopted: "no",
    userId: 3,
  },
  {
    name: "Minnie",
    age: "3 meses",
    species: "gato",
    image:
      "https://i.pinimg.com/474x/e3/98/64/e39864f7f4f7c3ae41e7a009379d8721.jpg",
    size: "pequeño",
    color: "siamesa",
    sex: "hembra",
    temperament: "juguetona",
    adopted: "no",
    userId: 5,
  },
];

const usersData = [
  {
    type: "admin",
    name: "admin",
    username: "admin",
    email: "huellitas2901@gmail.com",
    address: "Henry",
    phone: "Henry",
    website: "Huellitas",
    facebook: "no",
    instagram: "huellitaswebpets",
    twitter: "Huellitas Web",
    tiktok: "no",
    description:
      "Administrador global, todos podemos usar este usuario como admin. Para iniciar sesión debemos cargarlo a la base de datos con un post a / y luego en el login ingresar por gmail con huellitas",
    image:
      "https://ucarecdn.com/c7c6c96a-edae-49bb-a723-a040d408ee16/",
    CVU: "826221765285480",
    status: "activo",
    password: "#huellitas1919",
  },
  {
    type: "usuario",
    name: "Ervin Howell",
    email: "Shanna@melissa.tv",
    address: "Victor Plains 879, Wisokyburgh, Cordoba",
    phone: "010-692-6593 x09125",
    website: "anastasia.net",
    facebook: "ErvinH",
    instagram: "ErvinH12",
    twitter: "ErvinHowell",
    tiktok: "ErvinMiRey",
    description: "Almorcé con una llama debajo de tu cama porque puedo",
    image:
      "https://this-person-does-not-exist.com/img/avatar-6be0ff0121b792fe397ba3e3b96e28fb.jpg",
    CVU: "",
    status: "activo",
    password: "1234",
  },
  {
    type: "usuario",
    name: "Clementine Bauch",
    username: "Samantha",
    email: "Nathan@yesenia.net",
    address: "Douglas Extension Suite 847, McKenziehaven, La Pampa",
    phone: "1-463-123-4447",
    website: "ramiro.info",
    facebook: "ClemBauch",
    instagram: "",
    twitter: "",
    tiktok: "ClemBauch",
    description: "Recibí una fuerte multa pero no logró aplastar mi espíritu",
    image:
      "https://this-person-does-not-exist.com/img/avatar-e49f2c746f6d712ce4261659c0430d79.jpg",
    CVU: "",
    status: "activo",
    password: "1234",
  },
  {
    type: "usuario",
    name: "Patricia Lebsack",
    username: "Karianne",
    email: "Julianne.OConner@kory.org",
    address: "Hoeger Mall Apt. 692, South Elvis, Formosa",
    phone: "493-170-9623 x156",
    website: "kale.biz",
    facebook: "PatoLeb",
    instagram: "PatoLeb123",
    twitter: "PatoPato",
    tiktok: "",
    status: "activo",
    description:
      "Ella insistió en que limpiar tu armario era la clave para una buena conducción",
    image:
      "https://this-person-does-not-exist.com/img/avatar-ab54e9a5a41010f6a08b075319bd36e4.jpg",
    CVU: "",
    password: "1234",
  },
  {
    type: "usuario",
    name: "Chelsey Dietrich",
    username: "Kamren",
    email: "Lucio_Hettinger@annie.ca",
    address: "Skiles Walks Suite 351, Roscoeview, Santa Fe",
    phone: "(254)954-1289",
    website: "demarco.info",
    facebook: "DemarcoRules",
    instagram: "parislove",
    twitter: "bebitofiufiu",
    tiktok: "reinadelbaile",
    status: "activo",
    description:
      "Ella le pidió prestado el libro hace muchos años y aún no lo ha devuelto",
    image:
      "https://this-person-does-not-exist.com/img/avatar-dc4c055e1246d39761bd6af9381a1ae9.jpg",
    CVU: "",
    password: "1234",
  },
  {
    type: "usuario",
    name: "Mrs. Dennis Schulist",
    username: "Leopoldo_Corkery",
    email: "Karley_Dach@jasper.info",
    address: "Norberto Crossing 950, South Christy, Buenos Aires",
    phone: "1-477-935-8478 x6430",
    website: "ola.org",
    facebook: "DemarcoRules",
    instagram: "parislove",
    twitter: "bebitofiufiu",
    tiktok: "reinadelbaile",
    status: "activo",
    description:
      "Tu novia compró tu cereal crujiente de galleta favorito pero se olvidó de comprar leche",
    image:
      "https://this-person-does-not-exist.com/img/avatar-105b76fcb7bc230cbb0368d85d72621d.jpg",
    CVU: "",
    password: "1234",
  },
  {
    type: "usuario",
    name: "Kurtis Weissnat",
    username: "Elwyn.Skiles",
    email: "Telly.Hoeger@billy.biz",
    address: "Rex Trail 280, Howemouth, Capital Federal",
    phone: "210.067.6132",
    website: "elvis.io",
    facebook: "KurtKurt",
    instagram: "Kurtina",
    twitter: "Kratos123",
    tiktok: "",
    status: "activo",
    description:
      "Seamos todos únicos juntos hasta que nos demos cuenta de que todos somos iguales",
    image:
      "https://this-person-does-not-exist.com/img/avatar-6b8e21a0a1a6b92dee39b6b8aa7c592e.jpg",
    CVU: "",
    password: "1234",
  },
  {
    type: "usuario",
    name: "Nicholas Runolfsdottir V",
    username: "Maxime_Nienow",
    email: "Sherwood@rosamond.me",
    address: "Ellsworth Summit 729, Aliyaview, Capital Federal",
    phone: "586.493.6943 x140",
    website: "jacynthe.com",
    facebook: "NicoNicoNi",
    instagram: "ElQuinto",
    twitter: "55Nico5",
    tiktok: "NicoPasion",
    status: "activo",
    description:
      "Aunque pensaba que el mundo era plano, no veía la ironía de querer viajar alrededor del mundo",
    image:
      "https://this-person-does-not-exist.com/img/avatar-f5a693b6ed7623e837d11f04015a9c06.jpg",
    CVU: "",
    password: "1234",
  },
  {
    type: "usuario",
    name: "Glenna Reichert",
    username: "Delphine",
    email: "Chaim_McDermott@dana.io",
    address: "Dayna Park 449, Bartholomebury, Cordoba",
    phone: "(775)976-6794 x41206",
    website: "conrad.com",
    facebook: "Enna",
    instagram: "EnaReich123",
    twitter: "",
    tiktok: "",
    description:
      "Solo quería decirte que pude ver el amor que sientes por tu hija por la forma en que la miras",
    image:
      "https://this-person-does-not-exist.com/img/avatar-2bb874b50c274716b5a6e3e6e41ec0ae.jpg",
    CVU: "",
    password: "1234",
  },
  {
    type: "usuario",
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    address: "Kattie Turnpike 198, Lebsackbury, Capital Federal",
    phone: "024-648-3804",
    website: "ambrose.net",
    facebook: "Clemmme1987",
    instagram: "Perritos99",
    twitter: "Perritos99",
    tiktok: "amolosperritos",
    description:
      "En el momento en que aterrizó comprendió la razón por la que se trataba de un estado de sobrevuelo",
    image:
      "https://this-person-does-not-exist.com/img/avatar-b43dff51af55240892c6c1505327b914.jpg",
    CVU: "",
    password: "1234",
  },
  {
    type: "fundacion",
    name: "Perritos Fundacion",
    username: "PerritosFundacion",
    email: "perritos@gmail.com",
    address: "Belgrano 198, Rio Tercero, Cordoba",
    phone: "024-648-3804",
    website: "perritos.net",
    facebook: "FundacionPerritos",
    instagram: "FundacionPerritos",
    twitter: "FundacionPerritos",
    tiktok: "",
    description:
      "Nuestro Centro de Adopciones está siempre abierto a quienes estén buscando una mascota para amar y cuidar.  Durante todo el año hay perritos de todas las edades, tamaños y colores esperando que lleguen sus nuevos humanos. ",
    image:
      "https://png.pngtree.com/template/20191017/ourlarge/pngtree-logo-illustration-dog-outline-pet-design-on-white-background-image_319750.jpg",
    CVU: "596013402768904",
    password: "1234",
  },
  {
    type: "fundacion",
    name: "De Patitas En La Calle",
    username: "depatitasenlacalle",
    email: "depatitasenlacalle@gmail.com",
    address: "Lamadrid 2530, San Miguel de Tucuman, Tucuman",
    phone: "381-648-3804",
    website: "depatitasenlacalle.net",
    facebook: "depatitasenlacalle",
    instagram: "depatitasenlacalle",
    twitter: "depatitasenlacalle",
    tiktok: "",
    description:
      "AYUDANOS A AYUDAR!Somos un Grupo que trabaja Ad Honorem, RESCATANDO,AYUDANDO ,CONCIENTIZANDO,",
    image:
      "https://villaelisacdn.s3.fr-par.scw.cloud/municipalidad/feriapatitas.jpg",
    CVU: "948360284814368",
    password: "1234",
  },
  {
    type: "fundacion",
    name: "Bigotes y Narices",
    username: "bigotesynarices",
    email: "bigotesynarices@gmail.com",
    address: "San Martin 1989, Salta, Salta",
    phone: "388-648-3804",
    website: "bigotesynarices.net",
    facebook: "bigotesynarices",
    instagram: "bigotesynarices",
    twitter: "bigotesynarices",
    tiktok: "",
    description:
      "El rescate y adopción de gatos es una experiencia gratificante y gratificante. Como todos los animales, los gatos requieren cuidado y atención. También son una delicia para tener en la familia.",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSOP2ddW8Ud2NC3k7zuo3PvCPESmflx5WLEQ&usqp=CAU",
    CVU: "842254369748662",
    password: "1234",
  },
  {
    type: "fundacion",
    name: "Fundacion Vida Animal",
    username: "vidaanimal",
    email: "vidaanimal@gmail.com",
    address: "Buenos Aires 968, Santa Rosa, La Pampa",
    phone: "11-648-3804",
    website: "vidaanimal.org.ar",
    facebook: "Fundacionvidaanimal",
    instagram: "vidaanimalFundacion",
    twitter: "vidaanimal",
    tiktok: "vidaanimal",
    description:
      "Fundación Vidanimal es una organización no gubernamental sin fines de lucro abocada a difundir, proteger y promover los derechos de los animales.",
    image:
      "https://www.vidanimal.org.ar/wp-content/uploads/2019/04/logo-vidanimal-blanco-original-300x268.png",
    CVU: "106672908060515",
    password: "1234",
  },
];

const campaignsData = [
  {
    title: "Lola necesita una operacion",
    reason: "Recaudar fondos para operación",
    description:
      "Lola es una perrita muy buena que fue rescatada hace poco, necesita una operacion de cadera porque fue atropellada. Por favor ayudanos a recaudar fondos para cubrir los gastos veterinarios",
    goal: 100000,
    image:
      "https://infofunes.com.ar/uploads/Marga%20perrita%20rescatada%202.png",
    userId: 11,
  },
  {
    title: "Refugio necesita dinero para alimento",
    reason: "Recaudar fondos para gastos diarios",
    description:
      "El refugio animal 'Patitas Frias' recibe hasta 10 animales rescatados por día. Son muchas bocas para alimentar asi que necesitamos colaboracion para poder darles de comer a todos",
    goal: 150000,
    image:
      "https://diarioresumen.com.ar/static/old/uploads/2020/01/Perros-calle-web.jpg",
    userId: 12,
  },
];

module.exports = { petsData, usersData, campaignsData };
